version: 2
jobs:
  run:
    working_directory: ~/stock-reporter
    docker:
      - image: circleci/node:8-jessie-browsers
    steps:
      - checkout
      - run:
          name: Changing the execution mode of the file
          command: 'chmod +x statsCollector.sh'
      - run:
          name: Fetching reports
          command: ./statsCollector.sh
workflows:
   version: 2
   nightly:
     triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - run
